### ISSUE TITLE
downloadWeigth 404 error

### ISSUE THREAD

**Issue by AnyKeyer** [grapeot/AnimeHeadDetector#2]
Can I have a working download link? No Chinese services please.

**Comment by devdevgoat** [comment]
Bump, @grapeot any chance you could help me get a copy, willing to host a NA mirror!

**Comment by grapeot** [comment]
Sorry for the late reply. Somehow github unwatched myself... I just fixed the download link. It's still https://lab.grapeot.me/head.weights. 

@devdevgoat appreciate your help! You can download the file through the original link.

Close the issue for now. But feel free to reopen it in case you need additional info.
