### ISSUE TITLE
The .sh file does not work

### ISSUE THREAD

**Issue by QuestionLife** [grapeot/AnimeHeadDetector#3]
flashes a command error then exits the shell

**Comment by QuestionLife** [comment]
https://lab.grapeot.me/head.weights

404 Error Not Found

**Comment by AnyKeyer** [comment]
Duplicate of #2

**Comment by grapeot** [comment]
Sorry for the late reply. Somehow github unwatched myself... I just fixed the download link. It's still https://lab.grapeot.me/head.weights.
